### ISSUE TITLE
Include branch information

### ISSUE THREAD

**Issue by nlohmann** [RPGillespie6/fastcov#1]
First of, great utility! Calculating the branch coverage is one of the slowest steps in our CI chain, and any speed up here greatly improves developer satisfaction.

#### My issue

However, to fully switch from lcov to fastcov, I am currently missing branch information.

#### What I tried

I compiled with GCC 9.0.1 and

```
CXXFLAGS="--coverage -g -O0 -fprofile-arcs -ftest-coverage"
```

After executing the test suite, I call

```
fastcov.py --lcov -o report.info --gcov /usr/local/bin/gcc9/gcov
genhtml --legend --demangle-cpp --output-directory html --show-details --branch-coverage report.info
```

does not show branch coverage.

#### What I expect

For lcov, there exists a dedicated switch like

```
--rc lcov_branch_coverage=1
```

to enable processing of branch coverage. Is this also possible somehow with fastcov?

**Comment by RPGillespie6** [comment]
It's true fastcov currently is ignoring branch information in the gcov files. This should be pretty easy to add, though - I just need to figure out how branch coverage is represented in lcov reports. I'll take a look tonight.

**Comment by RPGillespie6** [comment]
You should be able to now pass `--branch-coverage` to fastcov to include branch coverage in the resulting .info file.

**Comment by nlohmann** [comment]
I can confirm that branch coverage information is now contained in the output. Thank you very much!

**Comment by RPGillespie6** [comment]
I tested it against your project as well as 2 of mine, and it looks good so I merged to master.

**Comment by nlohmann** [comment]
I checked the master version and can confirm it works. Thanks a lot!
