### ISSUE TITLE
How to get the basic block execution path of the program based on the coverage.json generated by fastcov?

### ISSUE THREAD

**Issue by zhangteng0526** [RPGillespie6/fastcov#103]
Is it possible to get the execution path of the program based on coverage.json? If so, how should I do it?

**Comment by RPGillespie6** [comment]
The coverage data only captures which lines were touched during execution, it doesn't capture the order in which functions were called, i.e. stack traces. For that you'll need a tracing such as GCC's [-finstrument-functions](https://stackoverflow.com/a/5818587/2516916) or [c++23's stacktrace](https://en.cppreference.com/w/cpp/header/stacktrace).

**Comment by RPGillespie6** [comment]
@zhangteng0526 Did this answer your question? I'm going to close this as stale, but we can continue the discussion if you still need help.
