### ISSUE TITLE
Error with non-utf8 source files

### ISSUE THREAD

**Issue by blueyed** [RPGillespie6/fastcov#14]
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/daniel/Vcs/fastcov/fastcov.py", line 196, in exclMarkerWorker
    for i, line in enumerate(f, 1): #Start enumeration at line 1
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 8135: invalid start byte
```

The file in question: https://github.com/vim/vim/blob/94f82cbacf76767b5ac32f813e1d670501dbd0e6/src/digraph.c

**Comment by blueyed** [comment]
The file might be strange (but Vim itself recognizes it as latin1).
`file -bi src/digraph.c` says: `text/x-c; charset=unknown-8bit`

**Comment by RPGillespie6** [comment]
Hmm, indeed, it looks like some of the comments in that file have `latin1` characters! Let me tinker around and see what the best way to handle this would be.

**Comment by blueyed** [comment]
A trivial / not-so-good patch would be:
```diff
diff --git i/fastcov.py w/fastcov.py
index 10ae65f..fa0d6fb 100755
--- i/fastcov.py
+++ w/fastcov.py
@@ -192,7 +192,7 @@ def exclMarkerWorker(fastcov_sources, chunk, exclude_branches_sw, include_branch

         start_line = 0
         end_line = 0
-        with open(source) as f:
+        with open(source, errors='ignore') as f:
             for i, line in enumerate(f, 1): #Start enumeration at line 1
                 if str(i) in fastcov_sources[source]["branches"]:
                     if all(not line.lstrip().startswith(e) for e in include_branches_sw): # Include branches starting with...
```

I think the best would be to read the whole file, and retry with different encoding(s) on failure, eventually falling back to ignoring errors.

**Comment by RPGillespie6** [comment]
Yes, I was thinking of doing the latter but having the user pass in the encodings their sources need as an option (i.e. `--fallback-encodings latin1`)

**Comment by blueyed** [comment]
Yeah, not a nice topic.. ;)
There are libs like chardet that might help (as a fallback).
A list of fallback-encodings sounds fine to begin with.
