### ISSUE TITLE
How to exclude source files

### ISSUE THREAD

**Issue by nlohmann** [RPGillespie6/fastcov#2]
#### My issue

The coverage report contains coverage information for system headers and unrelated source files.

#### What I tried

Calling fastcov.py as described in #1.

Using `--exclude-gcda` seems inapplicable, because I do not want to exclude `.gcda` files, but their content for certain files or directories, like `/usr/include`.

I also tried `lcov -e` to clean up the generated lcov file, but it always seems to wipe out the whole report, leaving a zero-byte file.

#### What I expect

A switch to either pass only the desired source files or directories, or a switch to pass source files or directories to exclude.

**Comment by nlohmann** [comment]
I figured the paths in the generated report are wrong (maybe some interference with CMake), and a simple sed script could fix them to be used with `lcov -e`.

**Comment by RPGillespie6** [comment]
Did you try `--exclude-gcov /usr/include`? It's not super clear but each gcov file maps to exactly one source file, so `--exclude-gcov /usr/include` would throw away any gcov files containing the substring `/usr/include`

**Comment by nlohmann** [comment]
I'll try.

**Comment by nlohmann** [comment]
Yes, `--exclude-gcov` works! It only took me a while to understand that multiple arguments need to be given with spaces, like so:

```
--exclude-gcov /usr 9.0.1/ test/
```

It would be helpful, however, to have support for explicit inclusion like "only give me coverage information for the following files", because such a list of sources can be easily generated inside a CMake project.

**Comment by RPGillespie6** [comment]
This should be easy enough to add as well. I'll plan on introducing 2 new options, one that's basically the exact opposite of `--exclude-gcov` which will allow you to whitelist source files with a substring pattern like `src/` and one which will take an explicit list of source files to be processed.

**Comment by RPGillespie6** [comment]
I've added 2 new options and renamed some others to hopefully be more intuitive. Note that `--exclude-gcov` is now just `--exclude`.

Filtering options:

```
  -s, --source-files
                        Filter: Specify exactly which source files should be
                        included in the final report. Paths must be either
                        absolute or relative to current directory.
  -e, --exclude
                        Filter: Exclude source files from final report if they
                        contain one of the provided substrings (i.e.
                        /usr/include test/, etc.)
  -i, --include
                        Filter: Only include source files in final report that
                        contain one of the provided substrings (i.e. src/
                        etc.)
```

If your case you could do either `--source-files ${CMAKE_GENERATED_SOURCES}` or, if all of your sources are in a common directory like `src/`, you could do: `--include src/`

**Comment by nlohmann** [comment]
There is still an issue I mentioned in https://github.com/RPGillespie6/fastcov/issues/2#issuecomment-478216535 but did not detail so far: The paths in the output of fastcov (and possibly internally) are wrong:

In my case, I have a CMake project with the following paths:

- sources: `/Users/niels/Documents/repositories/json/include`
- CMake build path: `/Users/niels/Documents/repositories/json/build_coverage`

However, in the generated info file, the sources have paths like `/Users/niels/Documents/repositories/json/build_coverage/include/nlohmann/json.hpp` which are invalid. They are a mix of the CMake build path followed by a relative suffix.

As a result, I get an error like

```
genhtml: ERROR: cannot read /Users/niels/Documents/repositories/json/build_coverage/include/nlohmann/json.hpp
```

My current fix is to call sed like

```
gsed -i 's%build_coverage/%%g' json.info
```

before calling `genhtml`. Due to these wrong paths, the options `-s` or `-i` do not work with the source list from CMake as fastcov cannot "find" the existing paths.

**Comment by nlohmann** [comment]
(Here is the call in the project: https://github.com/nlohmann/json/blob/feature/fastcov/test/CMakeLists.txt#L58)

**Comment by RPGillespie6** [comment]
Let me try building coverage for your project.

**Comment by nlohmann** [comment]
Thanks!! You can check out the branch and call `make fast-cov`.

**Comment by RPGillespie6** [comment]
Ok, I _think_ I know what the issue is. The issue is that one of the constraints of fastcov is that it needs to be invoked from the same directory as the compiler (or told where that directory is with `--compiler-directory`). Currently it is being invoked from `test/` instead of from `build_coverage/`. I think passing `--compiler-directory ..` should fix it, but I'll test it out and confirm.

**Comment by nlohmann** [comment]
I gave it a quick try and tried passing `--compiler-directory` with `..`,  `${CMAKE_SOURCE_DIR}`, and `${CMAKE_BINARY_DIR}`, but nothing worked :-/

**Comment by RPGillespie6** [comment]
Yes, I've confirmed there is a problem when fastcov is invoked from outside of the compiler directory.

This works:
```
build_dir$ python3 ../test/thirdparty/fastcov/fastcov.py --branch-coverage --lcov -o json.info -s ../single_include/nlohmann/json.hpp
build_dir$ genhtml --title "JSON for Modern C++" --legend --demangle-cpp --output-directory html --show-details --branch-coverage json.info
```

But this doesn't:
```
build_dir/test$ python3 ../../test/thirdparty/fastcov/fastcov.py --branch-coverage --lcov -o json.info -s ../../single_include/nlohmann/json.hpp --compiler-directory ..
build_dir$ genhtml --title "JSON for Modern C++" --legend --demangle-cpp --output-directory html --show-details --branch-coverage json.info
```
This should be fairly simple to figure out though. I'll keep you updated.

**Comment by RPGillespie6** [comment]
No wait, actually I had messed up my docker mount with the previous comment.

It seems like it's working for me as-is:

```
$ git clone https://github.com/nlohmann/json.git
$ cd json
$ docker run -it --rm -v "$PWD":/build_env -w /build_env -u $(id -u):$(id -g) rpgillespie6/fastcov
$ mkdir build
$ cd build
$ cmake .. -DJSON_Coverage=YES
...
$ make -j4
...
$ ctest -j4
...
$ time make lcov_html2
42 .gcda files
Spawned 4 gcov processes each processing at most 11 gcda files
1949 .gcov files generated by gcov
41 .gcov files processed by fastcov (1908 skipped)
Created lcov info file 'json.info'
Reading data file json.info.filtered.noexcept
Found 1 entries.
Found common filename prefix "/build_env/json/single_include"
Writing .css and .png files.
Generating output.
Processing file nlohmann/json.hpp
Writing directory view page.
Overall coverage rate:
  lines......: 98.9% (4643 of 4694 lines)
  functions..: 74.8% (2759 of 3687 functions)
  branches...: 91.3% (1367 of 1498 branches)
[100%] Built target lcov_html2

real	0m3.970s
user	0m6.551s
sys	0m0.855s
```

(Note I modified your `test/CMakeLists.txt` to comment out `gsed` and to filter on `json.hpp`:
```
    add_custom_target(lcov_html2
        COMMAND ${CMAKE_SOURCE_DIR}/test/thirdparty/fastcov/fastcov.py --branch-coverage --lcov -o json.info -s ${CMAKE_SOURCE_DIR}/single_include/nlohmann/json.hpp
        --gcov ${GCOV_BIN}
        # COMMAND gsed -i 's%build_coverage/%%g' json.info
        COMMAND ${CMAKE_SOURCE_DIR}/test/thirdparty/imapdl/filterbr.py json.info > json.info.filtered.noexcept
        COMMAND genhtml --title "JSON for Modern C++" --legend --demangle-cpp --output-directory html --show-details --branch-coverage json.info.filtered.noexcept
        COMMENT "Generating HTML report test/html/index.html"
    )
```

I think there is still may be a path problem, but now I'm having trouble reproducing it. 

How are you invoking the unit tests and building the coverage?

**Comment by RPGillespie6** [comment]
Oh wait, I bet I know what it is... are you using `ninja` instead of `make`? `ninja` and `make` generated build system pass `-I` flags differently (known issue: https://gitlab.kitware.com/cmake/cmake/issues/13894.)

I see that `lcov_html2` does crash if I use `ninja`. Shouldn't be hard to work around.

**Comment by RPGillespie6** [comment]
Ok, I think I've fixed it.

Can you try again? You'll need to add `--compiler-directory ${CMAKE_BINARY_DIR}` to the fastcov invocation, as well as remove the `gsed` line.

**Comment by nlohmann** [comment]
Thanks so much for looking into this. I can confirm that `--compiler-directory ${CMAKE_BINARY_DIR}` works now!

However, I still struggle with excluding source files via `--source-files`. I try to pass `${SOURCE_FILES}` which is a space-separated list of absolute paths to all source files I'm interested in. My full call looks like this:

```
/Users/niels/Documents/repositories/json/test/thirdparty/fastcov/fastcov.py --branch-coverage --lcov -o json.info --gcov /Users/niels/Documents/projects/compilers/local/bin/gcov --compiler-directory /Users/niels/Documents/repositories/json/build_coverage --source-files /Users/niels/Documents/repositories/json/include/nlohmann/adl_serializer.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/conversions/from_json.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/conversions/to_chars.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/conversions/to_json.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/exceptions.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/input/binary_reader.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/input/input_adapters.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/input/json_sax.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/input/lexer.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/input/parser.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/input/position_t.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/iterators/internal_iterator.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/iterators/iter_impl.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/iterators/iteration_proxy.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/iterators/iterator_traits.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/iterators/json_reverse_iterator.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/iterators/primitive_iterator.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/json_pointer.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/json_ref.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/macro_scope.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/macro_unscope.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/meta/cpp_future.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/meta/detected.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/meta/is_sax.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/meta/type_traits.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/meta/void_t.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/output/binary_writer.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/output/output_adapters.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/output/serializer.hpp /Users/niels/Documents/repositories/json/include/nlohmann/detail/value_t.hpp /Users/niels/Documents/repositories/json/include/nlohmann/json.hpp /Users/niels/Documents/repositories/json/include/nlohmann/json_fwd.hpp
```

However, this is the output:

```
Spawned 5 gcov processes each processing at most 10 gcda files
2450 .gcov files generated by gcov
0 .gcov files processed by fastcov (2450 skipped)
Created lcov info file 'json.info'
```

I double checked: the exact paths can be found in the `json.info` file if generated without `--source-files`.

**Comment by RPGillespie6** [comment]
I think I may have fixed this on master with [this recent commit](https://github.com/RPGillespie6/fastcov/commit/befd2552f8f7b1b64a6d08264bd6145bba85d5f9#diff-83945b7eec1e27359fbd41ddeb009f1dR107).

Could you try one more time?

At any rate, I was able to build `json` like this:
```
$ cmake .. -DJSON_Coverage=YES -DJSON_MultipleHeaders=YES -GNinja
$ ninja
$ ctest -j8
$ ninja lcov_html2 -v
[1/1] cd /build_env/json/fastcov2_build/test && /build_env/json/test/thirdparty/fastcov/fastcov.py --branch-coverage --lcov -o json.info --gcov /usr/local/bin/gcov --compiler-directory /build_env/json/fastcov2_build --source-files /build_env/json/include/nlohmann/adl_serializer.hpp /build_env/json/include/nlohmann/detail/conversions/from_json.hpp /build_env/json/include/nlohmann/detail/conversions/to_chars.hpp /build_env/json/include/nlohmann/detail/conversions/to_json.hpp /build_env/json/include/nlohmann/detail/exceptions.hpp /build_env/json/include/nlohmann/detail/input/binary_reader.hpp /build_env/json/include/nlohmann/detail/input/input_adapters.hpp /build_env/json/include/nlohmann/detail/input/json_sax.hpp /build_env/json/include/nlohmann/detail/input/lexer.hpp /build_env/json/include/nlohmann/detail/input/parser.hpp /build_env/json/include/nlohmann/detail/input/position_t.hpp /build_env/json/include/nlohmann/detail/iterators/internal_iterator.hpp /build_env/json/include/nlohmann/detail/iterators/iter_impl.hpp /build_env/json/include/nlohmann/detail/iterators/iteration_proxy.hpp /build_env/json/include/nlohmann/detail/iterators/iterator_traits.hpp /build_env/json/include/nlohmann/detail/iterators/json_reverse_iterator.hpp /build_env/json/include/nlohmann/detail/iterators/primitive_iterator.hpp /build_env/json/include/nlohmann/detail/json_pointer.hpp /build_env/json/include/nlohmann/detail/json_ref.hpp /build_env/json/include/nlohmann/detail/macro_scope.hpp /build_env/json/include/nlohmann/detail/macro_unscope.hpp /build_env/json/include/nlohmann/detail/meta/cpp_future.hpp /build_env/json/include/nlohmann/detail/meta/detected.hpp /build_env/json/include/nlohmann/detail/meta/is_sax.hpp /build_env/json/include/nlohmann/detail/meta/type_traits.hpp /build_env/json/include/nlohmann/detail/meta/void_t.hpp /build_env/json/include/nlohmann/detail/output/binary_writer.hpp /build_env/json/include/nlohmann/detail/output/output_adapters.hpp /build_env/json/include/nlohmann/detail/output/serializer.hpp /build_env/json/include/nlohmann/detail/value_t.hpp /build_env/json/include/nlohmann/json.hpp /build_env/json/include/nlohmann/json_fwd.hpp && /build_env/json/test/thirdparty/imapdl/filterbr.py json.info > json.info.filtered.noexcept && genhtml --title JSON\ for\ Modern\ C++ --legend --demangle-cpp --output-directory html --show-details --branch-coverage json.info.filtered.noexcept
[0.006s] Found 42 .gcda files 
[0.005s] Spawned 4 gcov threads, each processing at most 11 gcda files
[2.022s] Processed 552 .gcov files (2460 total, 1908 skipped)
[0.089s] Aggregated raw gcov JSON into fastcov JSON report
[0.002s] Spawned 4 threads each scanning at most 6 source files
[0.005s] Scanned 23 source files for exclusion markers
[0.012s] Created lcov info file 'json.info'
Reading data file json.info.filtered.noexcept
Found 22 entries.
Found common filename prefix "/build_env/json/include"
Writing .css and .png files.
Generating output.
Processing file nlohmann/adl_serializer.hpp
Processing file nlohmann/json.hpp
Processing file nlohmann/detail/json_ref.hpp
Processing file nlohmann/detail/value_t.hpp
Processing file nlohmann/detail/exceptions.hpp
Processing file nlohmann/detail/json_pointer.hpp
Processing file nlohmann/detail/conversions/to_chars.hpp
Processing file nlohmann/detail/conversions/to_json.hpp
Processing file nlohmann/detail/conversions/from_json.hpp
Processing file nlohmann/detail/input/position_t.hpp
Processing file nlohmann/detail/input/json_sax.hpp
Processing file nlohmann/detail/input/parser.hpp
Processing file nlohmann/detail/input/lexer.hpp
Processing file nlohmann/detail/input/binary_reader.hpp
Processing file nlohmann/detail/input/input_adapters.hpp
Processing file nlohmann/detail/iterators/iter_impl.hpp
Processing file nlohmann/detail/iterators/json_reverse_iterator.hpp
Processing file nlohmann/detail/iterators/iteration_proxy.hpp
Processing file nlohmann/detail/iterators/primitive_iterator.hpp
Processing file nlohmann/detail/output/binary_writer.hpp
Processing file nlohmann/detail/output/output_adapters.hpp
Processing file nlohmann/detail/output/serializer.hpp
Writing directory view page.
Overall coverage rate:
  lines......: 100.0% (4641 of 4641 lines)
  functions..: 74.8% (2759 of 3687 functions)
  branches...: 91.7% (1366 of 1490 branches)
```

**Comment by nlohmann** [comment]
I can confirm that it works now! Thanks a lot for taking the time to fix the issues!

**Comment by RPGillespie6** [comment]
Thanks for trying out fastcov! I wasn't really expecting users until after GCC 9's official launch!

**Comment by nlohmann** [comment]
FYI: I merged the fast-cov branch of nlohmann/json. It's now part of the maintainer tool suite I use to prepare releases. I may check it at work next week where the coverage CI step currently takes 50 minutes...

**Comment by RPGillespie6** [comment]
Great, let me know how it goes. I'd be interested to know:

- How many gcda/gcov files the 50 minute CI step involves
- How many cores the CI runner has access to
- How long it takes with fastcov

Currently with fastcov, ~50% of the time is spent waiting for gcov itself to chew through the gdcas, ~50% of the time is spent parsing the json output of gcov and consolidating it into a single in-memory data structure. 

If I knew roughly the size of your project I may be able to generate a mock one that has a similar gcda/gcov count for profiling purposes.

In fastcov there may be room for improvement by using a faster JSON parser (though vanilla Python3 is pretty fast). There may also be room for improvement with GCC 9's new compiler flags `-fprofile-filter-files` and `-fprofile-exclude-files` (see https://gcc.gnu.org/onlinedocs/gcc.pdf). If gcov itself becomes the main bottleneck, we could get https://github.com/marxin involved (he's the primary gcov maintainer).
