### ISSUE TITLE
Feature request: add ability to merge .info files together

### ISSUE THREAD

**Issue by f18m** [RPGillespie6/fastcov#32]
Hi,
it would be really nice to have in fastcov the same option that lcov provides, i.e. the --add-tracefile option which allows you to merge together .lcov files (or .info files in fastcov case). 
This allows to merge contributes from different runs of the same source tree from e.g. different containers...

**Comment by RPGillespie6** [comment]
Are you using `genhtml`? If so, I _believe_ you can combine them with `cat` and `genhtml` will handle it correctly :

```
$ cat coverage1.info coverage2.info coverage3.info > coverage_final.info
$ genhtml coverage_final.info -o html_report
```

That said, I'll look into seeing how hard it would be to add that feature into fastcov itself
