### ISSUE TITLE
Out of source builds produce coverage for generated files

### ISSUE THREAD

**Issue by PhilipMourdjis** [RPGillespie6/fastcov#33]
When running fastcov in `project/src/build`  no coverage info is produced for generated source files that are created in this build directory. This is expected.

When running fastcov from a build directory that is a sibling of a source directory (`project/build`). Generated source files are included in the coverage report and I do not know how to exclude them from the report (adding ../build/ to the exclude folders list has no effect).

**Comment by RPGillespie6** [comment]
Are the generated source files in `project/src/build`? If so, you'll want to add `--exclude ../src/build`

**Comment by PhilipMourdjis** [comment]
When cmake+ctest+fastcov are invoked from `project/src/build` the generated files are in `project/src/build` and they do not end up in the report.

When cmake+ctest+fastcov are invoked from `project/build` the generated files are in `project/build` and they are included in the report.

I would like to be able to build in `project/build` without the generated files showing up.

**Comment by RPGillespie6** [comment]
In that case you should be able to do `--exclude build/` and it will exclude any source file inside of `project/build/`. Or, if your generated file names have some kind of pattern like `gen_x.cpp`,  `gen_y.cpp`, etc. you could do `--exclude gen_` or you could make it so the generated files go into their own directory like `project/build/generated` and then just `--exclude generated/`.

Alternatively, you can only include the source files you want with `--include ../src` or include the source files you want explicitly with `--source-files ${SOURCE_FILES}`

If that doesn't help I'll need to know a few more details on the directory layout of your project.

**Comment by PhilipMourdjis** [comment]
`--exclude build/` doesn't work for me, this feels like a bug as these are automatically ignored in the case where the build directory is a subfolder of the src directory. I'll fork the example script here to see if I can show a minimal example of this but don't have time to do it this evening.

**Comment by RPGillespie6** [comment]
Fastcov will never automatically ignore source files that are linked to test binaries, so if it is not including them, either one of the CLI flags is filtering them, or there is a different reason behind it. A minimum example would be great, I would be able to tell exactly what is happening.

**Comment by PhilipMourdjis** [comment]
I have modified the example project in a fork of this repo: https://github.com/PhilipMourdjis/fastcov/tree/Ignore_build_directory
```
cd example
./build.sh
```
The ignore_me.cpp file generated by cmake is included in the example.json output even after attempts to exclude the build directory

**Comment by RPGillespie6** [comment]
I see what the problem is. This is actually related to #17 . It is a quirk with CMake/Ninja where it appears that files in the build directory use relative paths while paths outside of the build directory use absolute paths. Switching the build system to use Make instead of Ninja "fixes" the issue.

However, I still consider this a bug in fastcov, so I will fix it so that fastcov converts all paths to absolute before filtering.

**Comment by RPGillespie6** [comment]
Could you please try the latest on master and see if it fixes your issues? I won't release/push to pypi until then.

**Comment by PhilipMourdjis** [comment]
Works great! Thanks
