### ISSUE TITLE
need cobertura format xml result

### ISSUE THREAD

**Issue by xingxinghuo1000** [RPGillespie6/fastcov#35]
I need cobertura.xml results.
This is helpful for a coverage platform to store intermediate xml result for all languages and display the ALL-IN-ONE html results for all languages

Thanks

**Comment by RPGillespie6** [comment]
This shouldn't be too hard to add. I'll look into it this week.

**Comment by RPGillespie6** [comment]
I've never used Cobertura. Could you please try this package: https://github.com/eriwen/lcov-to-cobertura-xml

And let me know if the lcov -> covertura conversion is good? If so, I can make fastcov produce the same output without the need for a second package.

**Comment by noahp** [comment]
I've been very successful using that lcov-to-cobertura package on the output of fastcov, for what it's worth!

**Comment by RPGillespie6** [comment]
That's good to know. @xingxinghuo1000 please use `lcov-to-cobertura` for now on the lcov output of fastcov until I can find time to implement similar functionality in native fastcov.

**Comment by RPGillespie6** [comment]
I changed my mind, I don't feel it's necessary to implement this since [lcov-to-cobertura](https://github.com/eriwen/lcov-to-cobertura-xml) exists and works. Please use that to convert lcov format to cobertura xml.

**Comment by xingxinghuo1000** [comment]
@RPGillespie6  Good to know that. I've been use lcov-to-cobertura for couple of month. It works well.
Besides,  when you use pypy(or numba), you'll get better performance.
