### ISSUE TITLE
Support LLVM gcov

### ISSUE THREAD

**Issue by alexjurkiewicz** [RPGillespie6/fastcov#36]
I tried running this with LLVM's gcov on macOS:

```
❯ fastcov --branch-coverage  --process-gcno --lcov -o main_coverage.info
gcov: Unknown command line argument '-v'.  Try: '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/gcov -help'
gcov: Did you mean '-a'?
gcov: Not enough positional command line arguments specified!
Must specify at least 1 positional argument: See: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/gcov -help
```

Does LLVM's gcov have the functionality required to support fastcov?

**Comment by RPGillespie6** [comment]
It depends on if LLVM's gcov json format uses the same schema as GNU's gcov json format. Also, there's the problem that LLVM gcov doesn't seem to have the ability to stream coverage information to stdout (a key feature of GNU gcov that fastcov relies on).

However, it looks like llvm-cov possibly already has the ability to do the same thing fastcov does, though? I could be wrong (I haven't used clang much). 

At least, according to these [docs](https://llvm.org/docs/CommandGuide/llvm-cov.html), it looks like you could pass `-format=lcov` and `-j4` (or however many cores you have). The main reason fastcov exists is that (as far as I could tell) there weren't any tools that could convert .gcna or .gcno to intermediate formats in parallel (i.e. taking advantage of all cpu cores/threads).

**Comment by RPGillespie6** [comment]
I'm going to close this issue as there are no plans to support LLVM gcov currently (unless LLVM gcov adds in stdout coverage streaming).

**Comment by jeremybettis** [comment]
I don't know about previous versions, but 15.0.0 supports `llvm-cov gcov --stdout` but it doesn't support `--json-output`. It does support the intermediate format, but gcov removed that.

Also if you request the intermediate format, then --stdout doesn't work, it always writes to .gcov files. Sigh.
