### ISSUE TITLE
Exclude before include

### ISSUE THREAD

**Issue by dscole** [RPGillespie6/fastcov#37]
In my project I want to restrict the coverage data to only source files inside the project, so I use `--include ${CMAKE_SOURCE_DIR}`. But, I also want to exclude the test files themselves from the coverage, so I would like to use `--exclude test/`. Unfortunately, this doesn't work, because in this code:

https://github.com/RPGillespie6/fastcov/blob/558f9da560d56af21564387cec34b615b18efc01/fastcov.py#L144

It seems like if there are any includes, the excludes are basically ignored. If I just move the handling of the excludes to before the includes, everything works as expected for me.
Is there any reason why includes would be first?

**Comment by RPGillespie6** [comment]
> It seems like if there are any includes, the excludes are basically ignored.

Indeed, I originally thought of `--include` and `--exclude` as being mutually exclusive options.

However, I suppose there's no reason we couldn't remove the mutual exclusion and then specify in the readme that if both are provided, `--exclude` takes precedence.
