### ISSUE TITLE
Feature request: combine coverage information for templated functions

### ISSUE THREAD

**Issue by nlohmann** [RPGillespie6/fastcov#4]
Maybe related to #1:

#### Problem description

In [nlohmann/json](https://github.com/nlohmann/json), I use templates a lot. For instance, I have a function to transform integers to strings with the number type templated as `NumberType`.

Inside the function, I need to decide whether the passed number is positive or not. Of course, the two branches of the `if` can only be covered when `NumberType` is signed, say for `std::int64_t`. For unsigned types, however, one branch of the if will never be covered.

In lcov's source browser, I have a single if in the templated function with 4 branches (2 for each type that exist in the test suite), but only 3 of them are covered (due to the reasons described above). I will never be able to fix this to 100% branch coverage unless I would split the code into two functions, one for signed types with the if, and one for unsigned without the if.

#### Feature request

It would be great if fastcov had a switch to combine all coverage information regardless of the template type. That is, in the example above, both branches of the if are covered, one of them twice (by both types) and one of them once (only by the test case of the signed type).

Maybe this could be useful for others, too...

**Comment by RPGillespie6** [comment]
Could you provide a small code sample that reproduces this behavior in lcov?

I tried to with the following:

test.hpp:
```
#include <iostream>

template<class NumberType>
void foo(NumberType n)
{
    if (n < 0)
        std::cout << "signed" << std::endl;
    else
        std::cout << "signed or unsigned" << std::endl;
}
```

And then my "tests":
```
#include "test.hpp"

int main()
{
    foo(1);
    foo(-1);
    foo<unsigned int>(5);
}
```

But this is what I get out of lcov:

![lcov](https://user-images.githubusercontent.com/9853156/55283527-5ff77080-5333-11e9-8a94-bfb041b18224.png)

Here are the commands I ran:
```
g++ main.cpp -fprofile-arcs -ftest-coverage 
lcov --zerocounters -d .
./a.out 
lcov -c --rc lcov_branch_coverage=1 --directory . --output-file main_coverage.info
genhtml --branch-coverage -o out/ main_coverage.info 
```
If I could reproduce what you are describing I could use it to study the various coverage files and come up with a way to implement the requested feature.

**Comment by nlohmann** [comment]
Thanks for the example. I tried with both GCC and Clang, and I can only reproduce the behavior above with Clang:

<img width="757" alt="Screen Shot 2019-03-31 at 07 26 34" src="https://user-images.githubusercontent.com/159488/55285170-7d095f00-5386-11e9-8339-2420c4f298b0.png">

[main_coverage.info.zip](https://github.com/RPGillespie6/fastcov/files/3026237/main_coverage.info.zip)

With GCC, I get full branch coverage. I'll now check with my project which may take a while.

**Comment by nlohmann** [comment]
I tried with the whole project: GCC 8 produces full branch coverage for templated examples. GCC 7 and Clang produce the incomplete coverage I reported. So my issue can be fixed by just using a more recent GCC version - just as fastcov is demanding anyway. Thanks for having a look!

**Comment by RPGillespie6** [comment]
Good to know! I may tackle clang coverage eventually (hopefully it's not as slow/annoying as lcov), but for now I am focusing on gcc coverage.
