### ISSUE TITLE
Print warnings on missing source files

### ISSUE THREAD

**Issue by RPGillespie6** [RPGillespie6/fastcov#53]
Currently fastcov does not catch file not found errors when scanning for exclusion markers.

It would provide better UX if fastcov instead printed a warning. fastcov will still exit with a non-zero return code in this case to keep backwards compatibility, but it will no longer show a stack trace.

**Comment by RPGillespie6** [comment]
@wsnyder I think that should be the last issue you had brought up. If everything looks good, I will tag  `v1.7`

**Comment by wsnyder** [comment]
Yes, thanks for your help, it's in deployment.

**Comment by RPGillespie6** [comment]
No problem.  Just curious, how long does it take fastcov to process coverage for your project (you had mentioned it took lcov ~45 minutes?)

**Comment by wsnyder** [comment]
With the new features it's now split between 9 fastcov joins on separate machines, each about 30 seconds.  So say 4.5 minutes total, a 10x improvement.  Plus I'm now doing branch coverage, so fastcov is handling more data.

**Comment by RPGillespie6** [comment]
Glad to hear it. I'm fairly certain that as of now, gcov itself is the current bottleneck in terms of making coverage report generation faster. So I will have to work with the GCC folks to figure out how to speed it up more. Combine operations and exclusion scanning could probably be optimized/sped up a bit more, but I'm guessing for most people gcov is what takes the majority of the time.

**Comment by wsnyder** [comment]
FWIW the time it takes to run the compiles and tests is now 5-10x the fastcov/gcov times, so I'm pretty happy where the timing is now.
