### ISSUE TITLE
exclProcessSource is inefficient

### ISSUE THREAD

**Issue by tbuyukliev** [RPGillespie6/fastcov#73]
when generating an lcov info file the scanExclusionMarkers step takes most time, of which exclProcessSource does all the work.

as example, in a large codebase that has few files with markers the info file generation takes 22 minutes. with the following hack in the beginning of exclProcessSource it comes down to 5.

```
--- fastcov.py.orig	2021-06-24 02:20:41.117557334 -0700
+++ fastcov.py	2021-06-24 02:31:23.808711740 -0700
@@ -443,6 +443,8 @@
 def exclProcessSource(fastcov_sources, source, exclude_branches_sw, include_branches_sw, fallback_encodings):
     start_line = 0
     end_line = 0
+    if os.system("grep -q -F LCOV_EXCL " + source) != 0:
+        return # No markers in this file.
     # Start enumeration at line 1 because the first line of the file is line 1 not 0
     for i, line in enumerate(getSourceLines(source, fallback_encodings), 1):
         # Cycle through test names (likely only 1)
```
and grep was called a lot
[info]: Spawned 50 threads each scanning at most 367 source files

i'm sure it can be optimized further. :)

**Comment by RPGillespie6** [comment]
Nice find. Yes, fastcov is doing a needless work in this function, I will add a check similar to yours to make sure the file has exclusion markers first before doing any work. I will try python native solution first, and if it's significantly slower than grep, I'll expose a command line option for specifying a faster grep

**Comment by RPGillespie6** [comment]
Out of curiosity, how many files total are being scanned? Are there over 10,000 files? I'm thinking, it may also be beneficial to use multi-processing instead of just multi-threading so multiple cores can be utilized.

**Comment by RPGillespie6** [comment]
Can you try this version of fastcov:

https://github.com/RPGillespie6/fastcov/blob/optimize_excl_markers/fastcov.py

And see how it compares to your grep solution? I added a native python grep-like check to beginning of the function, shuffled/added some conditionals in the main loop, and switched from a multi-threading approach to a multi-process approach (so multiple cores should be used now).

Depending on your feedback we may be able to speed it up any more with:
- Using faster grep method
- Spawning multiple threads _per core_

**Comment by tbuyukliev** [comment]
> Out of curiosity, how many files total are being scanned? Are there over 10,000 files?

over 18000.

> https://github.com/RPGillespie6/fastcov/blob/optimize_excl_markers/fastcov.py

this one finished in 20 seconds. i think we're good now. :) i should have tried the python solution first.

**Comment by RPGillespie6** [comment]
Native python solution is roughly equivalent to your grep solution. I think the other speedup was using multiple cores instead of single core. 

I might be able to speed it up even more... does your machine really have 50 cores (or did you pass `--jobs 50`)? If so I could have it spawn ~10 threads per core which might make it even faster than 20 seconds.

**Comment by RPGillespie6** [comment]
(feel free to continue discussion even though issue is closed)

**Comment by tbuyukliev** [comment]
the machine has 50 cores and is actually a VM. if you want to experiment with other speedups i can try them out, up to you. thanks for the current fix.

**Comment by RPGillespie6** [comment]
Just for kicks.... try this one out and see if it's any faster:

https://github.com/RPGillespie6/fastcov/blob/multithreaded_lcov_exclusion/fastcov.py

The only difference is that this one will spawn 50 threads _per core_. So basically fastcov will spawn 50 processes (one per core) and each process will spawn 50 threads. Let me know if it results in a significant speedup or not from the 20 seconds.

**Comment by tbuyukliev** [comment]
this one has some problem. it didn't finish in over an hour and i stopped it.

**Comment by RPGillespie6** [comment]
Ok, I may revisit later when I can test locally on a project with 18k+ files, but I think the one on master should be good enough for now.
