### ISSUE TITLE
Options --scan-exclusion-markers/--skip-exclusion-markers and --validate-sources

### ISSUE THREAD

**Issue by johan-boule** [RPGillespie6/fastcov#81]
In a CI scenario, I've encountered a problem after a .cpp source file was removed from the repository.
We use incremental builds on the CI server and our build system is far from perfect (CMake), so it's not removing the derived files that where produced by the former .cpp, i.e., we still have the .o and .gcno files lying around.
When fastcov is called without the --skip-exclusion-markers, it's bailing out because it can't find the source file.

Perhaps fastcov's behaviour could be adjusted so that it doesn't fail in this case unless the --validate-sources option was also used ?

**Comment by RPGillespie6** [comment]
I guess the question is...  will this proposed change cause undesirable behavior in anyone else's CI pipelines? Hard to know if other people might be assuming and relying on fastcov failing if there is a missing exclusion source file.

What if instead we just add an option `--skip-missing-exclusion-sources` which, if set, won't write a non-zero exit code if an exclusion source couldn't be found?

That will also prevent fastcov tests from failing. We can add a new test for the flag here: https://github.com/RPGillespie6/fastcov/blob/master/test/functional/run_all.sh#L163

We can basically just copy paste that test, but add `--skip-missing-exclusion-sources` and then check `test $rc -eq 0`

If you update your PR to do that I'll merge it.

**Comment by snakethatlovesstaticlibs** [comment]
Hi @RPGillespie6, I'm also looking for this feature. If I implement it, are you open to merging it?

**Comment by RPGillespie6** [comment]
Sure, open to PRs. Feature would need to be backwards compatible with existing users, which is why I recommended making a new flag `--skip-missing-exclusion-sources`

**Comment by johan-boule** [comment]
Sorry to have left this as is without further work on implementing the suggestion for a new comman line flag.
I also ended up just putting the skip-exclusion-marker option.

**Comment by snakethatlovesstaticlibs** [comment]
No worries! I also used `--ignore-errors source" for genhtml (for future readers). Thanks for the great library @RPGillespie6! It's greatly sped up our pipeline

**Comment by RPGillespie6** [comment]
I'm going to close this issue as it appears the current CLI can cover the use cases described here, but we can re-open if needed.
