### ISSUE TITLE
Adding custom line exclusion marker (with same result as LCOV_EXCL_LINE)

### ISSUE THREAD

**Issue by timmey09** [RPGillespie6/fastcov#86]
To exclude coverage for lines like e.g. logging, debugging etc. it might be useful to offer an argument to pass custom exclusion marker with the same behavior as `LCOV_EXCL_LINE`. 

e.g. 
```C++
int i = 1;
if (i)
    std::cout << i;
else 
    LOG_ERROR("illegal number"); // <-- line to be excluded from coverage 
```

With passing `--custom_exclusion_maker LOG` to fastcov the wanted line should be excluded from the coverage without adding an additional `// LCOV_EXCL_LINE`. 

A similar algorithm is already implemented for checking to exclude keys in branch coverage.

**Comment by RPGillespie6** [comment]
Fastcov partially supports this. You can use the flag `--exclude-br-lines-starting-with LOG_` to exclude branch coverage of lines starting with `LOG_`. I suppose I could add support to exclude the whole line as well.

**Comment by timmey09** [comment]
Thanks for your reply. 
We are already using the branch exclusion but we want to to exclude lines too.

I already implemented the feature and will submit a PR soon. 

And additional "nice to have" would be the possibility to even remove the branch evaluation if one of the branches results in an empty branch after clearing a line:

```
std::string evaluateData(std::string_view val)
{
    std::string ret;
    if (val == "some data") // <-- remove negative branch as the else branch is empty after ignoring LOG line
        ret.assign(val).append(" evaluated!");
    else
        LOG_AND_SHOW_ERROR("val not set"); // <-- ignore line 
    return ret;
}
```

**Comment by RPGillespie6** [comment]
As for your other request, it might be a little tricky. I recommend restructuring your C++ to either use "early exit" strategy which avoids need for negative branches:

```
std::string evaluateData(std::string_view val)
{
    std::string ret;
    if (val == "some data")
        return ret.assign(val).append(" evaluated!");

    LOG_AND_SHOW_ERROR("val not set");
    return ret;
}
```

Or just baking the condition into your function/macro itself similar to assert:
```
std::string evaluateData(std::string_view val)
{
    std::string ret;
    bool evaluated = (val == "some data");

    LOG_AND_SHOW_ERROR(!evaluated, "val not set"); // Only logs error if condition is !evaluated

    if (evaluated)
        ret.assign(val).append(" evaluated!");

    return ret;
}
```

**Comment by timmey09** [comment]
I opened PR #87 without testing. If find the time I will add the corresponding test case.

Regarding the branch evaluation if lines are removed: 
For my (maybe too) simple example, you are absolutely right. However, restructuring the C++ code is unfortunately not an option for the real cases.

But I agree: Adding this feature to fastcov isn't a reasonable option at all.

**Comment by RPGillespie6** [comment]
Can you confirm this issue is now resolved on the latest commit on master?

**Comment by timmey09** [comment]
The issue is resolved. Thanks a lot for your support.
