### ISSUE TITLE
without docker, how to quickly generate coverage report.

### ISSUE THREAD

**Issue by jianhe-fun** [RPGillespie6/fastcov#98]
the following assume I have docker. but I don't have docker.

```
$ docker pull rpgillespie6/fastcov
$ docker run -it --rm -v ${PWD}:/mnt/workspace -w /mnt/workspace -u $(id -u ${USER}):$(id -g ${USER}) rpgillespie6/fastcov
$ <build project> # Make sure to compile with gcc-9 or g++-9 and to pass "-g -O0 -fprofile-arcs -ftest-coverage" to all gcc/g++ statements
$ <run unit tests>
$ fastcov.py --gcov gcov-9 --exclude /usr/include --lcov -o report.info
$ genhtml -o code_coverage report.info
$ firefox code_coverage/index.html
```

now I have 
coverage.info
coverage.info.initial
coverage.info.raw
coverage.info.run

use fastcov, I can more quickly generate cover html file for me? can you tell me how to do this without docker.
what I tried: `python3 fastcov.py --gcov gcov-9 --lcov -o coverage.info`

**Comment by RPGillespie6** [comment]
Does this solve the problem? Feel free to re-open if I didn't address your concern.
